### ISSUE TITLE
client version 1.44 is too new

### ISSUE THREAD

**Issue by KawaKode** [semanser/codel#54]
Hi, 

I tried to run Codel on my Docker server and it says that the Docker client is too new, is there a way to bypass this or do I have to wait it out ?

![image](https://github.com/semanser/codel/assets/75862028/832506ed-843c-4ba1-bdef-dd0e40767e34)

Here's my compose : 
```yaml
name: codel-ai
services:
    codel:
        image: ghcr.io/semanser/codel:latest
        environment:
            - OLLAMA_MODEL=llama2
            - GIN_MODE=release
        ports:
            - 3010:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
```
